# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-22.04

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm install .
      npm link
      npm run lint # this is how we build, at least for now
    displayName: "npm install and build"

  - script: |
      npm run test-ci

  - task: PublishTestResults@2
    displayName: "supply npm test results to pipelines"
    condition: succeededOrFailed() # because otherwise we won't know what tests failed
    inputs:
      testResultsFiles: "coverage/junit.xml"
